package pl.spiascik.ug.app.service;

import pl.spiascik.ug.app.domain.Cloth;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class ClothServiceJDBC implements ClothService {
    private Connection connection;

    private String url = "jdbc:hsqldb:hsql://localhost/workdb";

    private String createTableCloth = "CREATE TABLE Cloth(id bigint GENERATED BY DEFAULT AS IDENTITY, name varchar(50) UNIQUE, productionDate DATE , price DECIMAL, isWaterproof BOOLEAN)";

    private String DELETE_ALL_CLOTHES = "DELETE FROM Cloth";

    private Statement statement;
    private PreparedStatement preparedStatement;


    public ClothServiceJDBC() {
        try {
            connection = DriverManager.getConnection(url);
            statement = connection.createStatement();

            ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
            boolean tableExists = false;
            while (rs.next()) {
                if ("Cloth".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    tableExists = true;
                    break;
                }
            }

            if (!tableExists)
                statement.executeUpdate(createTableCloth);

            preparedStatement = connection.prepareStatement("INSERT INTO Cloth (name, productionDate, price, isWaterproof) VALUES (?,?,?,?)");

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    Connection getConnection() {
        return connection;
    }

    @Override
    public void addCloth(Cloth cloth) throws SQLException {

//        boolean result = false;
        try {
            preparedStatement.setString(1, cloth.getName());
            preparedStatement.setDate(2, new java.sql.Date(cloth.getProductionDate().getTime()));
            preparedStatement.setDouble(3, cloth.getPrice());
            if(cloth.isWaterproof())
                preparedStatement.setBoolean(4, true);
            else
                preparedStatement.setBoolean(4, false);
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void removeCloth(String name) throws SQLException {

        try {
            String sql = "DELETE FROM Cloth " +
                    "WHERE name='"+name+"'";
//            System.out.println(sql);
            statement.executeUpdate(sql);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public List<Cloth> getListOfClothes() throws SQLException {
        List<Cloth> clothes = new ArrayList<Cloth>();
        Cloth cloth;

        statement = connection.createStatement();
        try {
            ResultSet rs = statement.executeQuery("SELECT id, name, productionDate, price, isWaterproof FROM Cloth");

            while (rs.next()) {
                cloth = new Cloth(rs.getString("name"), rs.getString("productionDate"), rs.getDouble("price"), rs.getBoolean("isWaterproof"));
                clothes.add(cloth);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return clothes;
    }

    @Override
    public void showAllClothes() throws SQLException {
        List<Cloth> clothes = getListOfClothes();

        for (Cloth cloth : clothes) {
            System.out.println(cloth.toString());
        }
    }

    @Override
    public void showAllWaterproof() throws SQLException {
        List<Cloth> clothes = getListOfClothes();

        for (Cloth cloth : clothes) {
            if(cloth.isWaterproof())
                System.out.println(cloth.toString());
        }
    }

    @Override
    public boolean addAllClothes(List<Cloth> clothes) {
        try {
            connection.setAutoCommit(false);
            for (Cloth cloth : clothes) {
                preparedStatement.setString(1, cloth.getName());
                preparedStatement.setDate(2, new java.sql.Date(cloth.getProductionDate().getTime()));
                preparedStatement.setDouble(3, cloth.getPrice());
                if(cloth.isWaterproof())
                    preparedStatement.setBoolean(4, true);
                else
                    preparedStatement.setBoolean(4, false);
                preparedStatement.executeUpdate();
            }
            connection.commit();
            return true;

        } catch (SQLException e) {
            System.out.println("Wycofanie transakcji");
            try {
                connection.rollback();
            } catch (SQLException e1) {
                System.out.println("Błąd wycofania");
                e1.printStackTrace();
            }
        }
        return false;
    }

    @Override
    public void searchName(String name) throws SQLException {
        List<Cloth> clothes = getListOfClothes();
        boolean found = false;
        for (Cloth cloth : clothes) {
            if (cloth.getName().equals(name)) {
                System.out.print("Znalazłem: ");
                System.out.print(cloth.toString());
                System.out.println("");

                found=true;
            }
        }
        if(!found)
            System.out.println("Nie znalazłem rekordów, nazwa: " + name);

    }
}
